version: "3.8"

services:
  mysql:
    image: mariadb:10
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: .
    container_name: backend-container
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  mysql-data: